### ISSUE TITLE
Replace flake8 with ruff

### ISSUE THREAD

**Issue by kevinbowen777** [kevinbowen777/django-start#179]
See: https://github.com/charliermarsh/ruff

**Comment by kevinbowen777** [comment]
Steps for replacing flake8 with ruff

1. Install ruff `poetry add --group -dev ruff`
2. Add template to `pyproject.toml` (see next comment for details)
3. Run `ruff check .`
4. Add ruff to `.pre-commit-commit-config.yml`
5. Determine flake8 removal steps (TBD)

**Comment by kevinbowen777** [comment]
Initial ruff configuration template for `pyproject.toml`

See also: 
  - https://github.com/charliermarsh/ruff
  - https://beta.ruff.rs/docs/configuration/
  - https://beta.ruff.rs/docs/settings/


```toml
[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".mypy_cache",
    ".nox",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "__pypackages__",
    "htmlcov",
    "migrations",
    "_build",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 79

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
```
